### ISSUE TITLE
FinTS sometimes weird transaction details field

### ISSUE THREAD

**Issue by e7p** [pretix/pretix-banktool#3]
Within our bank (Sparkasse Bochum) the transaction details are stored in the `purpose` field of the transaction data instead of the `transaction_details` field, which is missing. A possible fix would be in the attached diff file which looks for a `purpose` field when the `transaction_details` are missing and would use this in the case it exists.
[purpose.txt](https://github.com/pretix/pretix-banktool/files/1370072/purpose.txt)

**Comment by Endres** [comment]
Actually I misunderstood the parse transaction data function a bit, though `transaction_details` is missing for me, so another patch would be more likely relevant to be applied to be able to support such banks as Sparkasse Bochum.
[purpose2.txt](https://github.com/pretix/pretix-banktool/files/1372064/purpose2.txt)

**Comment by jfwiebe** [comment]
Hi,
I have the same issue, the "Hannoversche Volksbank" is also missing this API. In my case, there is no `transaction_details` field, instead there is a `purpose` field, but the value of this field is `EVENTID-ORDERID IBAN:DE1234567890123 BIC:ABCDEFGH`. (Why do you do this, bank? every value has their own field in the standard and you are even using it correctly, why putting it into the purpose, too?)

**Comment by raphaelm** [comment]
purpose is read these days
