### ISSUE TITLE
pretix-banktool 1.0.0 requires click==6.*, but pretix requires click>=8.1.2

### ISSUE THREAD

**Issue by navlisilvan** [pretix/pretix-banktool#4]
"pretix-banktool 1.0.0 requires click==6.*, but you have click 8.1.3 which is incompatible."

pretix requires click>=8.1.2

so what to do?

**Comment by wiffbi** [comment]
As banktool only communicates with pretix through its HTTP-REST API, it does not need to share the same `env`. So maybe try to install banktool outside of pretix in another `env` as described in the README.

**Comment by mweinelt** [comment]
I think that was resolved with #6.
