### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by sysadminpower2019** [pretix/pretix-banktool#5]
it has been a long time since there has been an update

**Comment by raphaelm** [comment]
yes but it still works, at least two entities are using it. it's a little niche though

**Comment by e7p** [comment]
Don't really see this project as niche, as with every instance of pretix you really want to automatically import bank transfers, in case you provide the option of using bank transfer payments. It simply doesn't seem to need to be updated.

**Comment by raphaelm** [comment]
It's niche in that 99% of pretix users do not know how to run a Python tool on a Linux server and therefore using this is not an option for them. At the same time, integrating this into pretix SaaS would be illegal (as account access services are regulated). Still, it works and is not dead.
